# Generated by Django 4.1.4 on 2023-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='writers',
            options={'verbose_name': 'Писатель', 'verbose_name_plural': 'Писатели'},
        ),
        migrations.AlterField(
            model_name='writers',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='фото'),
        ),
    ]
