# Generated by Django 4.2.2 on 2024-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_writers_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='вопрос/отзыв')),
            ],
            options={
                'verbose_name': 'Вопрос/отзыв',
                'verbose_name_plural': 'Вопросы/отзывы',
            },
        ),
        migrations.RemoveField(
            model_name='writers',
            name='id',
        ),
        migrations.AlterField(
            model_name='writers',
            name='back',
            field=models.ImageField(default='', upload_to='img/', verbose_name='задник'),
        ),
        migrations.AlterField(
            model_name='writers',
            name='surname',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='фамилия на английском'),
        ),
    ]
